function producer_consumer( ...
    videofile,...
    consumer_threads, ...
    OMP_threads, ...
    timeout, ...
    timeflag)

maxNumCompThreads(OMP_threads);
in_queue = parallel.pool.PollableDataQueue;
out_queue = parallel.pool.DataQueue;
afterEach(out_queue,@disp)

if timeflag
    num_frames = time_exec( ...
        videofile, ...
        in_queue, ...
        out_queue, ...
        consumer_threads, ...
        timeout ...
        );
else
    num_frames = start( ...
        videofile, ...
        in_queue, ...
        out_queue, ...
        consumer_threads, ...
        timeout ...
        );
end

    function frame_num = producer(videofile,in_queue,out_queue)
        mov = VideoReader(videofile);
        frame_num = 0;
        while mov.hasFrame
            frame = mov.readFrame();
            frame_gray = frame(:,:,1);
            frame_num = frame_num + 1;
            send(in_queue, frame_gray)
        end
    end

    function consumer(in_queue,out_queue,timeout,cid)
        while 1
            [frame, ok] = poll(in_queue, timeout);
            send(out_queue,ok)
            if ok
                process(frame);
            else
                break
            end
        end
    end

    function process(frame)
        imwrite(frame,'test.png','png');
    end

    function num_frames = start( ...
            videofile, ...
            in_queue, ...
            out_queue, ...
            consumer_threads, ...
            timeout ...
            )
        prod = parfeval(@producer,1,videofile,in_queue,out_queue);
        cons = cell(consumer_threads,1);
        for i=1:consumer_threads
            cons{i} = parfeval(@consumer,0,in_queue,out_queue,timeout,i);
        end

        wait(prod)
        num_frames = fetchOutputs(prod);
        for i=1:consumer_threads
            wait(cons{i})
        end
    end

    function num_frames = time_exec(videofile, ...
            in_queue, ...
            out_queue, ...
            consumer_threads, ...
            timeout ...
            )
        starttime = tic;
        num_frames = start(videofile,in_queue,out_queue,consumer_threads,timeout);
        dur = toc(starttime);
        fps = num_frames/dur;
        disp(["Num_frames: " + num2str(num_frames) +...
            ", Time elapsed: " + num2str(dur) +...
            ", FPS: " + num2str(fps)])
    end
end